services:
  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3006:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec rails server -b 0.0.0.0"
    tty: true
    stdin_open: true
    volumes:
      - .:/rails
      - /rails/tmp
      - /rails/log
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development

volumes:
  bundle:
  mysql_data:
