services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle exec rails server -b 0.0.0.0 -p 3000"
    tty: true
    volumes:
      - .:/rails
      - /rails/tmp
      - /rails/log
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development

volumes:
  bundle:
